Ea definition support
infobloxopen/infoblox-ansible pull request #235
Opened 2024-07-03 07:06 UTC by JkhatriInfobox

2024-07-04 04:59 UTC, JchhatbarInfoblox commented on tests/unit/plugins/modules/test_nios_a_record.py
> +        wapi.update_object = Mock(name='update_object', )
remove extra comma.

2024-07-04 05:02 UTC, JchhatbarInfoblox requested changes
Update requested changes

2024-07-09 10:21 UTC, JkhatriInfobox commented on tests/unit/plugins/modules/test_nios_a_record.py
> +        wapi.update_object = Mock(name='update_object', )
Fixed

2024-07-09 10:29 UTC, JchhatbarInfoblox approved these changes
LGTM

2024-07-09 10:29 UTC, merged